### ISSUE TITLE
Tween Componet display error

### ISSUE THREAD

**Issue by BIGWGY** [Ahmed310/Widget-Manager---Unity3D#2]
my unity version is 

![image](https://github.com/Ahmed310/Widget-Manager---Unity3D/assets/13144389/a4d06495-c544-4fcf-9105-79dfedc1d4e1)

There have two issue!

one is the add component button display not correctly!

![image](https://github.com/Ahmed310/Widget-Manager---Unity3D/assets/13144389/a01117bf-bc4b-41fc-904a-8e6a494c33af)

another one is when open the component which inherit Widget class, unity editor will always hint you the prefab dirty.

![image](https://github.com/Ahmed310/Widget-Manager---Unity3D/assets/13144389/ed7a352f-67e8-4b7d-95d3-8fe87e60aab8)

**Comment by Ahmed310** [comment]
@BIGWGY  It's been a while I haven't updated this plugin. I will update the Editor UI logic so that it will work fine in latest versions of Unity.

**Comment by Ahmed310** [comment]
@BIGWGY you can keep it open till I update it. BTW are you still using this plugin?

**Comment by BIGWGY** [comment]
Yes, I still using this plugin! Thank you for your work very much.

**Comment by Ahmed310** [comment]
@BIGWGY above issues has been addressed take latest pull and make sure to revert your changes. 
Thanks for pointing out the issues I have added your name to the contributors list.

**Comment by BIGWGY** [comment]
OK!
